In [2]:
from pathlib import Path

# Change this path if you want the project somewhere else
project_root = Path("document-table-agent")

folders = [
    project_root / "app",
    project_root / "app" / "parsers",
    project_root / "app" / "extraction",
    project_root / "app" / "validation",
    project_root / "app" / "transformation",
    project_root / "app" / "agent",
    project_root / "app" / "export",
    project_root / "tests",
    project_root / "sample_documents",
    project_root / "outputs",
    project_root / "notebooks",
]

for folder in folders:
    folder.mkdir(parents=True, exist_ok=True)

print(f"Project created at: {project_root.resolve()}")

Project created at: C:\Users\vinee\document-table-agent\document-table-agent

In [3]:
files = [
    project_root / "app" / "__init__.py",
    project_root / "app" / "parsers" / "__init__.py",
    project_root / "app" / "parsers" / "pdf_parser.py",
    project_root / "app" / "extraction" / "__init__.py",
    project_root / "app" / "extraction" / "table_extractor.py",
    project_root / "app" / "validation" / "__init__.py",
    project_root / "app" / "validation" / "table_validator.py",
    project_root / "app" / "transformation" / "__init__.py",
    project_root / "app" / "transformation" / "transformer.py",
    project_root / "app" / "agent" / "__init__.py",
    project_root / "app" / "agent" / "request_parser.py",
    project_root / "app" / "export" / "__init__.py",
    project_root / "app" / "export" / "csv_exporter.py",
    project_root / "tests" / "test_extraction.py",
    project_root / "requirements.txt",
    project_root / "README.md",
    project_root / ".gitignore",
]

for file in files:
    file.touch(exist_ok=True)

print("Starter files created.")

Starter files created.

In [4]:
%pip install pymupdf pdfplumber pandas

Requirement already satisfied: pymupdf in d:\anaconda3\lib\site-packages (1.28.0)
Requirement already satisfied: pdfplumber in d:\anaconda3\lib\site-packages (0.11.10)
Requirement already satisfied: pandas in d:\anaconda3\lib\site-packages (3.0.5)
Requirement already satisfied: pdfminer.six==20260107 in d:\anaconda3\lib\site-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in d:\anaconda3\lib\site-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in d:\anaconda3\lib\site-packages (from pdfplumber) (5.12.1)
Requirement already satisfied: charset-normalizer>=2.0.0 in d:\anaconda3\lib\site-packages (from pdfminer.six==20260107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in d:\anaconda3\lib\site-packages (from pdfminer.six==20260107->pdfplumber) (46.0.3)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: cffi>=2.0.0 in d:\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in d:\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.23)
Requirement already satisfied: six>=1.5 in d:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
for path in project_root.rglob("*"):
    print(path)

document-table-agent\.gitignore
document-table-agent\app
document-table-agent\notebooks
document-table-agent\outputs
document-table-agent\README.md
document-table-agent\requirements.txt
document-table-agent\sample_documents
document-table-agent\tests
document-table-agent\app\agent
document-table-agent\app\export
document-table-agent\app\extraction
document-table-agent\app\parsers
document-table-agent\app\transformation
document-table-agent\app\validation
document-table-agent\app\__init__.py
document-table-agent\sample_documents\Weekly 300326 to 050426_544 (1).pdf
document-table-agent\tests\test_extraction.py
document-table-agent\app\agent\request_parser.py
document-table-agent\app\agent\__init__.py
document-table-agent\app\export\csv_exporter.py
document-table-agent\app\export\__init__.py
document-table-agent\app\extraction\table_extractor.py
document-table-agent\app\extraction\__init__.py
document-table-agent\app\parsers\pdf_parser.py
document-table-agent\app\parsers\__init__.py
document-table-agent\app\transformation\transformer.py
document-table-agent\app\transformation\__init__.py
document-table-agent\app\validation\table_validator.py
document-table-agent\app\validation\__init__.py

In [6]:
import os

print(os.getcwd())

C:\Users\vinee\document-table-agent

In [9]:
from pathlib import Path

project_root = Path.cwd() / "document-table-agent"

print("Project root:", project_root)
print("Exists:", project_root.exists())

Project root: C:\Users\vinee\document-table-agent\document-table-agent
Exists: True

In [10]:
pdf_folder = project_root / "sample_documents"

pdf_files = list(pdf_folder.glob("*.pdf"))

print("PDF files found:")

for pdf in pdf_files:
    print("-", pdf.name)

PDF files found:
- Weekly 300326 to 050426_544 (1).pdf

In [11]:
pdf_path = pdf_files[0]

print("Using PDF:")
print(pdf_path)

Using PDF:
C:\Users\vinee\document-table-agent\document-table-agent\sample_documents\Weekly 300326 to 050426_544 (1).pdf

In [12]:
import fitz

doc = fitz.open(pdf_path)

print("PDF opened successfully")
print("Number of pages:", len(doc))

PDF opened successfully
Number of pages: 6

In [13]:
for page_number in range(len(doc)):
    page = doc[page_number]
    text = page.get_text()

    print("=" * 70)
    print(f"PAGE {page_number + 1}")
    print("=" * 70)
    print(text[:1000])
    print()

======================================================================
PAGE 1
======================================================================

National Load Despatch Centre
राष्ट्रीय भार प्रेषण केंद्र
GRID CONTROLLER OF INDIA LIMITED
ग्रिड कंट्रोलर ऑफ इंग्रडया ग्रलग्रिट्ेड

(Government of India Enterprise/ भारत सरकार का उद्यि)
B-9, QUTUB INSTITUTIONAL AREA, KATWARIA SARAI, NEW DELHI -110016
बी-9, क़ुतुब इन्स्टीट्यूशनल एररया, कट्वाररया सराय, न्यू ग्रिल्ली-110016
_______________________________________________________________________________________________________________________________________
Ref: GRID-INDIA/NLDC/SO/Weekly Report                                                                           Date: 08th Apr 2026

To,

1. कार्यपालक निदेशक, पू. क्षे. भा. प्रे. के., 14, गोल्फ क्लब रोड , कोलकाता - 700033
Executive Director, ERLDC, 14 Golf Club Road, Tolleygunge, Kolkata, 700033
2. कार्यपालक निदेशक, ऊ. क्षे. भा. प्रे. के., 18/ ए , शहीद जीत स िंह  ि िवाल मागय, िई ददल्ली – 110016
Executive Director, NRLDC, 18-A, Shaheed Jeet Singh Marg, Katwaria Sarai, New Delhi – 110016
3. कार्यपालक निदेशक, प. क्षे. भा

======================================================================
PAGE 2
======================================================================
8-Apr-26
क्षेत्र
Region
दिन ांक Date
म ांग आपूर्ति
Demand Met
कमी
Shortage
म ांग आपूर्ति
Demand Met
कमी
Shortage
म ांग आपूर्ति
Demand Met
कमी
Shortage
म ांग आपूर्ति
Demand Met
कमी
Shortage
म ांग आपूर्ति
Demand Met
कमी
Shortage
म ांग आपूर्ति
Demand Met
कमी
Shortage
30-03-2026
58835
66938
58202
27540
174
2825
214340
174
31-03-2026
56296
70190
58004
27876
2864
215230
01-04-2026
58159
9
63748
55677
28540
2768
208892
9
02-04-2026
59052
62752
55600
29403
2973
209780
03-04-2026
53679
66432
56161
28058
552
3014
207344
552
04-04-2026
51850
64599
55461
30647
3070
205627
05-04-2026
52583
62624
52116
26683
2819
196825
ऊर् ि आपूर्ति
Energy Met
पनबिर्ली उत्प िन
Hydro Generation
ऊर् ि आपूर्ति
Energy Met
पनबिर्ली उत्प िन
Hydro Generation
ऊर् ि आपूर्ति
Energy Met
पनबिर्ली उत्प िन
Hydro Generation
ऊर् ि आपूर्ति
Energy Met
पनबिर्ली उत्प िन
Hydro Generation
ऊर् ि आपूर्ति
Energy Met
पनबिर्ली उत्प िन
Hydro Generation
ऊर् ि आपूर्ति
Energy Met
पनबिर्ली उत्प िन
Hydro Generation
30-03-2

======================================================================
PAGE 3
======================================================================
दिन ांक Date
र ज्य
States
दिन के
िौर न
अग्रिकतम
म ांग आपूर्ति
Max.
Demand
Met during
the day
अग्रिकतम
म ांग के
समय कमी
Peak hr
Shortage
दिन के
िौर न
अग्रिकतम
म ांग आपूर्ति
Max.
Demand
Met during
the day
अग्रिकतम
म ांग के
समय कमी
Peak hr
Shortage
दिन के
िौर न
अग्रिकतम
म ांग आपूर्ति
Max.
Demand
Met during
the day
अग्रिकतम
म ांग के
समय कमी
Peak hr
Shortage
दिन के
िौर न
अग्रिकतम
म ांग आपूर्ति
Max.
Demand
Met during
the day
अग्रिकतम
म ांग के
समय कमी
Peak hr
Shortage
दिन के
िौर न
अग्रिकतम
म ांग आपूर्ति
Max.
Demand
Met during
the day
अग्रिकतम
म ांग के
समय कमी
Peak hr
Shortage
दिन के
िौर न
अग्रिकतम
म ांग आपूर्ति
Max.
Demand
Met during
the day
अग्रिकतम
म ांग के
समय कमी
Peak hr
Shortage
दिन के
िौर न
अग्रिकतम
म ांग आपूर्ति
Max.
Demand
Met during
the day
अग्रिकतम
म ांग के
समय कमी
Peak hr
Shortage
पांर् ि Punjab
7517
0
7441
0
7540
0
7579
0
7875
0
7277
0
6607
0
िररय ण  Haryana
7940
0
7225
0
7944
0
8489
0
7529
0
8302
0
7166
0
र र्स

======================================================================
PAGE 4
======================================================================
क्षेत्र Region
र ज्य States
30-03-2026
31-03-2026
01-04-2026
02-04-2026
03-04-2026
04-04-2026
05-04-2026
पांर् ि Punjab
154.8
150.2
151.3
157.1
158.0
154.2
140.1
िररय ण  Haryana
158.5
154.2
150.2
158.9
155.8
153.1
132.6
र र्स्ि न Rajasthan
266.3
240.2
239.6
246.9
233.3
226.0
222.2
दिल्ली Delhi
93.0
84.4
88.9
93.6
93.4
88.4
85.5
उिर प्रिेश UP
422.6
423.3
395.5
429.2
411.5
373.3
344.2
उिर िांड Uttarakhand
42.9
42.6
41.7
41.8
44.5
43.9
39.5
दिम िल प्रिेश HP
32.7
30.8
29.9
31.0
32.1
31.4
28.4
र्म्मू और कचमीर J&K
52.8
48.9
43.1
51.7
52.8
51.2
53.1
िांडीगढ़ Chandigarh
4.0
3.8
4.0
4.0
4.0
3.9
3.5
रेलवे Railways_NR ISTS
4.2
4.1
4.2
4.2
4.2
4.2
4.3
छिीसगढ़ Chhattisgarh
149.6
146.6
147.9
152.7
152.9
150.8
140.7
गुर्र त Gujarat
471.1
473.6
449.0
450.2
450.0
447.1
426.5
मध्य प्रिेश MP
274.7
269.2
277.7
268.3
253.5
264.4
254.0
मि र ष्ट्ट्र Maharashtra
659.1
617.0
636.3
589.9
582.2
605.2
590.2
गोव  Goa
17.1
17.4
17.5
17.1
16.4
17.0
15.4
ि िर  और नगर िवेली एवां िमन और
िीव DNHDDPDCL
29.3
29.3
27.1
26

======================================================================
PAGE 5
======================================================================
ऊर् ि त्तवर्नमय
(लमललयन यूर्नर्ट्स)
Energy Exchange
(In MU)
दिवसीय
लशिर (मेग व ट)
 Day Peak
(MW)
दिवसीय औसत
(मेग व ट)
Day Average
(MW)
ऊर् ि त्तवर्नमय
(लमललयन यूर्नर्ट्स)
Energy Exchange
(In MU)
दिवसीय
लशिर (मेग व ट)
 Day Peak
(MW)
दिवसीय औसत
(मेग व ट)
Day Average
(MW)
ऊर् ि त्तवर्नमय
(लमललयन यूर्नर्ट्स)
Energy Exchange
(In MU)
दिवसीय
लशिर (मेग व ट)
 Day Peak
(MW)
दिवसीय औसत
(मेग व ट)
Day Average
(MW)
30-03-2026
-6.5
-611.1
-270
-5.0
-651
-209
-25.8
-1124
-1074
31-03-2026
-4.7
-629.6
-196
-6.6
-674
-274
-23.7
-1045
-989
01-04-2026
-6.9
-546.3
-286
-4.3
-584
-181
-24.6
-1079
-1026
02-04-2026
-9.5
-984.3
-395
-8.4
-730
-349
-25.3
-1082
-1054
03-04-2026
-7.8
-974.6
-324
-10.0
-694
-416
-24.8
-1064
-1032
04-04-2026
-6.9
-849.4
-288
-7.3
-427
-303
-25.6
-1115
-1067
05-04-2026
-4.3
-514.1
-178
-8.1
-811
-337
-26.1
-1128
-1088
कुल Total
-46.5
-49.6
-175.9
6. भूट न , नेप ल एवां ि ांग्ल िेश के स ि अांतरर ष्ट्ट्रीय त्तवद्युत त्तवर्नमय
INTERNATIONAL EXCHANGE WITH BHUTAN, NEPAL AN

======================================================================
PAGE 6
======================================================================
दिन ांक Date
30-03-2026
31-03-2026
01-04-2026
02-04-2026
03-04-2026
04-04-2026
05-04-2026
पूवि से उिर
East to North
-40.2
-26.8
-8.9
0.4
-1.4
32.6
18.7
पूवि से पश्चिम
East to West
-14.0
-1.4
3.6
16.1
32.9
44.8
39.8
पूवि से िक्षक्षण
East to South
-126.2
-121.9
-118.2
-110.6
-116.1
-116.8
-117.8
पूवि से उिर-पूवि
East to North-East
9.3
2.1
-8.6
-5.1
-5.9
-12.4
-8.1
उिर-पूवि से उिर
North-East to North
8.5
6.3
-7.5
-7.5
-7.6
-7.5
-7.7
पश्चिम से उिर
West to North
-1.3
10.6
-59.8
-34.9
-69.4
-47.1
-20.2
पश्चिम से िक्षक्षण
West to South
-236.0
-213.4
-201.5
-199.6
-201.6
-212.8
-198.5
7. अांतक्षेत्रीय त्तवर्नमय (लम०यू०) [प्रिम  क्षेत्र से  द्त्तवतीय क्षेत्र को आय त (+) / र्नय ित (-) ]
Inter-regional exchange (MU) [Import (+) / Export (-) from first region to second region]
Page 5 of 5

In [14]:
search_terms = [
    "Maximum Demand Met",
    "Energy Consumption"
]

for term in search_terms:
    print(f"\nSearching for: {term}")

    for page_number in range(len(doc)):
        text = doc[page_number].get_text()

        if term.lower() in text.lower():
            print(f"Found on page {page_number + 1}")

Searching for: Maximum Demand Met
Found on page 3

Searching for: Energy Consumption
Found on page 4

In [15]:
table_searches = {
    "maximum_demand": "Maximum Demand Met",
    "energy_consumption": "Energy Consumption"
}

found_pages = {}

for table_name, search_term in table_searches.items():
    matches = []

    for page_index in range(len(doc)):
        text = doc[page_index].get_text()

        if search_term.lower() in text.lower():
            matches.append(page_index + 1)

    found_pages[table_name] = matches

print(found_pages)

{'maximum_demand': [3], 'energy_consumption': [4]}

In [16]:
energy_page_number = found_pages["energy_consumption"][0]

energy_page = doc[energy_page_number - 1]

energy_text = energy_page.get_text()

print(energy_text)

क्षेत्र Region
र ज्य States
30-03-2026
31-03-2026
01-04-2026
02-04-2026
03-04-2026
04-04-2026
05-04-2026
पांर् ि Punjab
154.8
150.2
151.3
157.1
158.0
154.2
140.1
िररय ण  Haryana
158.5
154.2
150.2
158.9
155.8
153.1
132.6
र र्स्ि न Rajasthan
266.3
240.2
239.6
246.9
233.3
226.0
222.2
दिल्ली Delhi
93.0
84.4
88.9
93.6
93.4
88.4
85.5
उिर प्रिेश UP
422.6
423.3
395.5
429.2
411.5
373.3
344.2
उिर िांड Uttarakhand
42.9
42.6
41.7
41.8
44.5
43.9
39.5
दिम िल प्रिेश HP
32.7
30.8
29.9
31.0
32.1
31.4
28.4
र्म्मू और कचमीर J&K
52.8
48.9
43.1
51.7
52.8
51.2
53.1
िांडीगढ़ Chandigarh
4.0
3.8
4.0
4.0
4.0
3.9
3.5
रेलवे Railways_NR ISTS
4.2
4.1
4.2
4.2
4.2
4.2
4.3
छिीसगढ़ Chhattisgarh
149.6
146.6
147.9
152.7
152.9
150.8
140.7
गुर्र त Gujarat
471.1
473.6
449.0
450.2
450.0
447.1
426.5
मध्य प्रिेश MP
274.7
269.2
277.7
268.3
253.5
264.4
254.0
मि र ष्ट्ट्र Maharashtra
659.1
617.0
636.3
589.9
582.2
605.2
590.2
गोव  Goa
17.1
17.4
17.5
17.1
16.4
17.0
15.4
ि िर  और नगर िवेली एवां िमन और
िीव DNHDDPDCL
29.3
29.3
27.1
26.9
28.4
28.7
26.7
एएमएनएसआईएल AMNSIL
20.6
19.6
20.5
20.8
18.3
19.0
19.4
ि ल्को BALCO
16.3
16.2
16.0
16.9
16.9
16.9
17.5
आर.आई.एल.र् मनगर
RIL Jamnagar
5.9
6.2
6.4
6.2
6.3
6.3
6.3
आांध्र प्रिेश Andhra Pradesh
264.0
261.8
257.6
261.3
265.2
265.9
262.5
तेलांग न  Telangana
341.1
297.5
319.3
324.1
326.8
324.3
313.9
कन िटक Karnataka
331.9
338.7
334.1
338.9
337.2
336.8
310.2
केरल Kerala
97.4
99.5
102.8
102.5
95.9
99.5
93.0
तलमलन डु Tamil Nadu
416.5
424.0
411.3
419.9
426.8
424.5
379.2
पुिुिेरी (पॉश्डडिेरी) Pondy
10.3
10.4
10.1
10.4
10.5
10.8
10.4
बिि र Bihar
128.5
132.3
134.7
136.7
134.9
144.2
133.7
डीवीसी DVC
69.9
68.7
68.7
70.8
69.5
71.7
68.2
झ रिांड Jharkhand
45.7
43.5
44.5
45.9
45.5
47.0
42.6
ओडडश  Odisha
139.9
144.3
145.4
141.7
136.7
147.2
136.6
पश्चिम िांग ल West Bengal
214.0
200.6
213.0
236.0
246.2
253.8
208.9
लसश्ककम Sikkim
1.7
1.8
1.8
1.8
1.8
1.7
1.3
रेलवे Railways_ER ISTS
0.3
0.2
0.2
0.2
0.3
0.2
0.2
अरुण िल प्रिेश
Arunachal Pradesh
3.3
3.3
2.7
2.9
3.2
3.0
3.0
असम Assam
29.0
30.8
38.1
30.5
32.5
32.8
30.7
मखणपुर Manipur
3.4
3.3
3.4
3.3
3.1
3.4
3.2
मेघ लय Meghalaya
6.2
6.0
5.6
5.8
5.7
6.3
5.7
लमर्ोरम Mizoram
2.0
2.1
2.0
2.1
2.0
2.0
2.1
न ग लैंड Nagaland
2.5
2.6
2.6
2.7
2.2
2.6
2.4
बत्रपुर  Tripura
3.7
3.9
4.7
5.4
5.6
5.6
5.1
4986.2
4852.6
4849.3
4910.4
4865.7
4868.4
4562.6
अखिल भ रतीय ALL INDIA
उ०पू०क्षे०
NER
5. र ज्यों में ऊर् ि िपत (लमललयन यूर्नर्ट्स)
Energy Consumption in States (MUs)
ि०क्षे०
SR
उ०क्षे०
NR
पू०क्षे०
ER
प०क्षे०
WR
Page 3 of 5

In [17]:
import pdfplumber

In [18]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[energy_page_number - 1]

    tables = page.extract_tables()

print("Number of tables detected:", len(tables))

Number of tables detected: 1

In [19]:
for table_index, table in enumerate(tables):

    print("\n" + "=" * 100)
    print(f"TABLE {table_index + 1}")
    print("=" * 100)

    print("Number of rows:", len(table))

    if len(table) > 0:
        print("Number of columns:", len(table[0]))

    print("\nFirst 10 rows:\n")

    for row in table[:10]:
        print(row)

====================================================================================================
TABLE 1
====================================================================================================
Number of rows: 42
Number of columns: 9

First 10 rows:

['5. र ज्यों में ऊर् ि िपत (लमललयन यर्ू नर्ट्स)\nEnergy Consumption in States (MUs)', None, None, None, None, None, None, None, None]
['क्षेत्र Region', 'र ज्य States', '30-03-2026', '31-03-2026', '01-04-2026', '02-04-2026', '03-04-2026', '04-04-2026', '05-04-2026']
['उ०क्षे०\nNR', 'पर्ां ि Punjab', '154.8', '150.2', '151.3', '157.1', '158.0', '154.2', '140.1']
[None, 'िररय ण Haryana', '158.5', '154.2', '150.2', '158.9', '155.8', '153.1', '132.6']
[None, 'र र्स्ि न Rajasthan', '266.3', '240.2', '239.6', '246.9', '233.3', '226.0', '222.2']
[None, 'दिल्ली Delhi', '93.0', '84.4', '88.9', '93.6', '93.4', '88.4', '85.5']
[None, 'उिर प्रिेश UP', '422.6', '423.3', '395.5', '429.2', '411.5', '373.3', '344.2']
[None, 'उिर िडां Uttarakhand', '42.9', '42.6', '41.7', '41.8', '44.5', '43.9', '39.5']
['', 'दिम िल प्रिेश HP', '32.7', '30.8', '29.9', '31.0', '32.1', '31.4', '28.4']
[None, 'र्म्मू और कचमीर J&K', '52.8', '48.9', '43.1', '51.7', '52.8', '51.2', '53.1']

In [20]:
import pandas as pd

In [23]:
for table_index, table in enumerate(tables):

    print(f"\nTABLE {table_index + 1}")

    temp_df = pd.DataFrame(table)

    display(temp_df.head(15))

TABLE 1

,0,1,2,3,4,5,6,7,8
0,5. र ज्यों में ऊर् ि िपत (लमललयन यर्ू नर्ट्स)\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र Region,र ज्य States,30-03-2026,31-03-2026,01-04-2026,02-04-2026,03-04-2026,04-04-2026,05-04-2026
2,उ०क्षे०\nNR,पर्ां ि Punjab,154.8,150.2,151.3,157.1,158.0,154.2,140.1
3,NaN,िररय ण Haryana,158.5,154.2,150.2,158.9,155.8,153.1,132.6
4,NaN,र र्स्ि न Rajasthan,266.3,240.2,239.6,246.9,233.3,226.0,222.2
5,NaN,दिल्ली Delhi,93.0,84.4,88.9,93.6,93.4,88.4,85.5
6,NaN,उिर प्रिेश UP,422.6,423.3,395.5,429.2,411.5,373.3,344.2
7,NaN,उिर िडां Uttarakhand,42.9,42.6,41.7,41.8,44.5,43.9,39.5
8,,दिम िल प्रिेश HP,32.7,30.8,29.9,31.0,32.1,31.4,28.4
9,NaN,र्म्मू और कचमीर J&K,52.8,48.9,43.1,51.7,52.8,51.2,53.1
10,NaN,िडां ीगढ़ Chandigarh,4.0,3.8,4.0,4.0,4.0,3.9,3.5
11,NaN,रेलवे Railways_NR ISTS,4.2,4.1,4.2,4.2,4.2,4.2,4.3
12,,छिीसगढ़ Chhattisgarh,149.6,146.6,147.9,152.7,152.9,150.8,140.7
13,NaN,गर्ु र त Gujarat,471.1,473.6,449.0,450.2,450.0,447.1,426.5
14,,मध्य प्रिेश MP,274.7,269.2,277.7,268.3,253.5,264.4,254.0

In [24]:
raw_energy_table = tables[0]

raw_energy_df = pd.DataFrame(raw_energy_table)

display(raw_energy_df)

,0,1,2,3,4,5,6,7,8
0,5. र ज्यों में ऊर् ि िपत (लमललयन यर्ू नर्ट्स)\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र Region,र ज्य States,30-03-2026,31-03-2026,01-04-2026,02-04-2026,03-04-2026,04-04-2026,05-04-2026
2,उ०क्षे०\nNR,पर्ां ि Punjab,154.8,150.2,151.3,157.1,158.0,154.2,140.1
3,NaN,िररय ण Haryana,158.5,154.2,150.2,158.9,155.8,153.1,132.6
4,NaN,र र्स्ि न Rajasthan,266.3,240.2,239.6,246.9,233.3,226.0,222.2
5,NaN,दिल्ली Delhi,93.0,84.4,88.9,93.6,93.4,88.4,85.5
6,NaN,उिर प्रिेश UP,422.6,423.3,395.5,429.2,411.5,373.3,344.2
7,NaN,उिर िडां Uttarakhand,42.9,42.6,41.7,41.8,44.5,43.9,39.5
8,,दिम िल प्रिेश HP,32.7,30.8,29.9,31.0,32.1,31.4,28.4
9,NaN,र्म्मू और कचमीर J&K,52.8,48.9,43.1,51.7,52.8,51.2,53.1
10,NaN,िडां ीगढ़ Chandigarh,4.0,3.8,4.0,4.0,4.0,3.9,3.5
11,NaN,रेलवे Railways_NR ISTS,4.2,4.1,4.2,4.2,4.2,4.2,4.3
12,,छिीसगढ़ Chhattisgarh,149.6,146.6,147.9,152.7,152.9,150.8,140.7
13,NaN,गर्ु र त Gujarat,471.1,473.6,449.0,450.2,450.0,447.1,426.5
14,,मध्य प्रिेश MP,274.7,269.2,277.7,268.3,253.5,264.4,254.0
15,प०क्षे०\nWR,मि र ष्ट्ट्र Maharashtra,659.1,617.0,636.3,589.9,582.2,605.2,590.2
16,NaN,गोव Goa,17.1,17.4,17.5,17.1,16.4,17.0,15.4
17,NaN,ि िर और नगर िवले ी एवां िमन और\nिीव DNHDDPDCL,29.3,29.3,27.1,26.9,28.4,28.7,26.7
18,NaN,एएमएनएसआईएल AMNSIL,20.6,19.6,20.5,20.8,18.3,19.0,19.4
19,NaN,ि ल्को BALCO,16.3,16.2,16.0,16.9,16.9,16.9,17.5
20,NaN,आर.आई.एल.र् मनगर\nRIL Jamnagar,5.9,6.2,6.4,6.2,6.3,6.3,6.3
21,ि०क्षे०,आध्रां प्रिेश Andhra Pradesh,264.0,261.8,257.6,261.3,265.2,265.9,262.5
22,NaN,तले गां न Telangana,341.1,297.5,319.3,324.1,326.8,324.3,313.9
23,NaN,कन िटक Karnataka,331.9,338.7,334.1,338.9,337.2,336.8,310.2
24,SR,केरल Kerala,97.4,99.5,102.8,102.5,95.9,99.5,93.0
25,NaN,तलमलन डु Tamil Nadu,416.5,424.0,411.3,419.9,426.8,424.5,379.2
26,NaN,पिु िु रे ी (पॉश्डडिरे ी) Pondy,10.3,10.4,10.1,10.4,10.5,10.8,10.4
27,,बिि र Bihar,128.5,132.3,134.7,136.7,134.9,144.2,133.7
28,पू०क्षे०\nER,डीवीसी DVC,69.9,68.7,68.7,70.8,69.5,71.7,68.2
29,NaN,झ रिडां Jharkhand,45.7,43.5,44.5,45.9,45.5,47.0,42.6
30,NaN,ओडडश Odisha,139.9,144.3,145.4,141.7,136.7,147.2,136.6
31,NaN,पश्चिम िगां ल West Bengal,214.0,200.6,213.0,236.0,246.2,253.8,208.9
32,NaN,लसश्ककम Sikkim,1.7,1.8,1.8,1.8,1.8,1.7,1.3
33,NaN,रेलवे Railways_ER ISTS,0.3,0.2,0.2,0.2,0.3,0.2,0.2
34,उ०पू०क्षे०\nNER,अरुण िल प्रिेश\nArunachal Pradesh,3.3,3.3,2.7,2.9,3.2,3.0,3.0
35,NaN,असम Assam,29.0,30.8,38.1,30.5,32.5,32.8,30.7
36,NaN,मखणपरु Manipur,3.4,3.3,3.4,3.3,3.1,3.4,3.2
37,NaN,मघे लय Meghalaya,6.2,6.0,5.6,5.8,5.7,6.3,5.7
38,NaN,लमर्ोरम Mizoram,2.0,2.1,2.0,2.1,2.0,2.0,2.1
39,NaN,न ग लडैं Nagaland,2.5,2.6,2.6,2.7,2.2,2.6,2.4
40,NaN,बत्रपरु Tripura,3.7,3.9,4.7,5.4,5.6,5.6,5.1
41,अखिल भ रतीय ALL INDIA,NaN,4986.2,4852.6,4849.3,4910.4,4865.7,4868.4,4562.6

In [25]:
print("Rows:", raw_energy_df.shape[0])
print("Columns:", raw_energy_df.shape[1])

Rows: 42
Columns: 9

In [26]:
print(raw_energy_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       13 non-null     str
 1   1       40 non-null     str
 2   2       41 non-null     str
 3   3       41 non-null     str
 4   4       41 non-null     str
 5   5       41 non-null     str
 6   6       41 non-null     str
 7   7       41 non-null     str
 8   8       41 non-null     str
dtypes: str(9)
memory usage: 6.0 KB
None

In [27]:
display(raw_energy_df.head(10))
display(raw_energy_df.tail(10))

,0,1,2,3,4,5,6,7,8
0,5. र ज्यों में ऊर् ि िपत (लमललयन यर्ू नर्ट्स)\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र Region,र ज्य States,30-03-2026,31-03-2026,01-04-2026,02-04-2026,03-04-2026,04-04-2026,05-04-2026
2,उ०क्षे०\nNR,पर्ां ि Punjab,154.8,150.2,151.3,157.1,158.0,154.2,140.1
3,NaN,िररय ण Haryana,158.5,154.2,150.2,158.9,155.8,153.1,132.6
4,NaN,र र्स्ि न Rajasthan,266.3,240.2,239.6,246.9,233.3,226.0,222.2
5,NaN,दिल्ली Delhi,93.0,84.4,88.9,93.6,93.4,88.4,85.5
6,NaN,उिर प्रिेश UP,422.6,423.3,395.5,429.2,411.5,373.3,344.2
7,NaN,उिर िडां Uttarakhand,42.9,42.6,41.7,41.8,44.5,43.9,39.5
8,,दिम िल प्रिेश HP,32.7,30.8,29.9,31.0,32.1,31.4,28.4
9,NaN,र्म्मू और कचमीर J&K,52.8,48.9,43.1,51.7,52.8,51.2,53.1

,0,1,2,3,4,5,6,7,8
32,NaN,लसश्ककम Sikkim,1.7,1.8,1.8,1.8,1.8,1.7,1.3
33,NaN,रेलवे Railways_ER ISTS,0.3,0.2,0.2,0.2,0.3,0.2,0.2
34,उ०पू०क्षे०\nNER,अरुण िल प्रिेश\nArunachal Pradesh,3.3,3.3,2.7,2.9,3.2,3.0,3.0
35,NaN,असम Assam,29.0,30.8,38.1,30.5,32.5,32.8,30.7
36,NaN,मखणपरु Manipur,3.4,3.3,3.4,3.3,3.1,3.4,3.2
37,NaN,मघे लय Meghalaya,6.2,6.0,5.6,5.8,5.7,6.3,5.7
38,NaN,लमर्ोरम Mizoram,2.0,2.1,2.0,2.1,2.0,2.0,2.1
39,NaN,न ग लडैं Nagaland,2.5,2.6,2.6,2.7,2.2,2.6,2.4
40,NaN,बत्रपरु Tripura,3.7,3.9,4.7,5.4,5.6,5.6,5.1
41,अखिल भ रतीय ALL INDIA,NaN,4986.2,4852.6,4849.3,4910.4,4865.7,4868.4,4562.6

In [29]:
raw_output_path = project_root / "outputs" / "raw_energy_consumption.csv"

raw_output_path.parent.mkdir(parents=True, exist_ok=True)

raw_energy_df.to_csv(
    raw_output_path,
    index=False,
    header=False
)

print("Saved successfully!")
print("Saved to:")
print(raw_output_path.resolve())

Saved successfully!
Saved to:
C:\Users\vinee\document-table-agent\document-table-agent\outputs\raw_energy_consumption.csv

In [30]:
print("Notebook working directory:")
print(Path.cwd())

print("\nProject root:")
print(project_root)

print("\nOutput folder exists:")
print((project_root / "outputs").exists())

print("\nCSV exists:")
print(raw_output_path.exists())

Notebook working directory:
C:\Users\vinee\document-table-agent

Project root:
C:\Users\vinee\document-table-agent\document-table-agent

Output folder exists:
True

CSV exists:
True