In [1]:
from pathlib import Path
import sys

import pandas as pd

project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

sample_documents = project_root / "sample_documents"
outputs = project_root / "outputs"

print("Project root:", project_root)
print("Sample documents exists:", sample_documents.exists())
print("Outputs exists:", outputs.exists())

Project root: C:\Users\vinee\document-table-agent
Sample documents exists: True
Outputs exists: True

In [2]:
%load_ext autoreload
%autoreload 2

In [4]:
from app.parsers.pdf_parser import (
    get_page_count,
    search_pdf
)

In [5]:
pdf_files = list(sample_documents.glob("*.pdf"))

if not pdf_files:
    raise FileNotFoundError(
        "No PDF files found in sample_documents."
    )

pdf_path = pdf_files[0]

print("Using PDF:")
print(pdf_path)

Using PDF:
C:\Users\vinee\document-table-agent\sample_documents\Weekly 300326 to 050426_544 (1).pdf

In [6]:
energy_pages = search_pdf(
    pdf_path,
    "Energy Consumption"
)

print("Energy Consumption pages:", energy_pages)

Energy Consumption pages: [4]

In [9]:
from app.extraction.table_extractor import (
    extract_tables_from_page,
    table_to_dataframe,
    extract_table_as_dataframe,
    get_table_shape
)

In [10]:
energy_page_number = energy_pages[0]

print("Selected Energy Consumption page:", energy_page_number)

Selected Energy Consumption page: 4

In [11]:
tables = extract_tables_from_page(
    pdf_path,
    energy_page_number
)

print("Tables detected:", len(tables))

Tables detected: 1

In [12]:
for index, table in enumerate(tables):

    shape = get_table_shape(table)

    print(
        f"Table {index}: "
        f"{shape['rows']} rows × "
        f"{shape['columns']} columns"
    )

Table 0: 42 rows × 9 columns

In [13]:
pd.DataFrame(tables[0])

,0,1,2,3,4,5,6,7,8
0,5. र ज्यों में ऊर् ि िपत (लमललयन यर्ू नर्ट्स)\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र Region,र ज्य States,30-03-2026,31-03-2026,01-04-2026,02-04-2026,03-04-2026,04-04-2026,05-04-2026
2,उ०क्षे०\nNR,पर्ां ि Punjab,154.8,150.2,151.3,157.1,158.0,154.2,140.1
3,NaN,िररय ण Haryana,158.5,154.2,150.2,158.9,155.8,153.1,132.6
4,NaN,र र्स्ि न Rajasthan,266.3,240.2,239.6,246.9,233.3,226.0,222.2
5,NaN,दिल्ली Delhi,93.0,84.4,88.9,93.6,93.4,88.4,85.5
6,NaN,उिर प्रिेश UP,422.6,423.3,395.5,429.2,411.5,373.3,344.2
7,NaN,उिर िडां Uttarakhand,42.9,42.6,41.7,41.8,44.5,43.9,39.5
8,,दिम िल प्रिेश HP,32.7,30.8,29.9,31.0,32.1,31.4,28.4
9,NaN,र्म्मू और कचमीर J&K,52.8,48.9,43.1,51.7,52.8,51.2,53.1
10,NaN,िडां ीगढ़ Chandigarh,4.0,3.8,4.0,4.0,4.0,3.9,3.5
11,NaN,रेलवे Railways_NR ISTS,4.2,4.1,4.2,4.2,4.2,4.2,4.3
12,,छिीसगढ़ Chhattisgarh,149.6,146.6,147.9,152.7,152.9,150.8,140.7
13,NaN,गर्ु र त Gujarat,471.1,473.6,449.0,450.2,450.0,447.1,426.5
14,,मध्य प्रिेश MP,274.7,269.2,277.7,268.3,253.5,264.4,254.0
15,प०क्षे०\nWR,मि र ष्ट्ट्र Maharashtra,659.1,617.0,636.3,589.9,582.2,605.2,590.2
16,NaN,गोव Goa,17.1,17.4,17.5,17.1,16.4,17.0,15.4
17,NaN,ि िर और नगर िवले ी एवां िमन और\nिीव DNHDDPDCL,29.3,29.3,27.1,26.9,28.4,28.7,26.7
18,NaN,एएमएनएसआईएल AMNSIL,20.6,19.6,20.5,20.8,18.3,19.0,19.4
19,NaN,ि ल्को BALCO,16.3,16.2,16.0,16.9,16.9,16.9,17.5
20,NaN,आर.आई.एल.र् मनगर\nRIL Jamnagar,5.9,6.2,6.4,6.2,6.3,6.3,6.3
21,ि०क्षे०,आध्रां प्रिेश Andhra Pradesh,264.0,261.8,257.6,261.3,265.2,265.9,262.5
22,NaN,तले गां न Telangana,341.1,297.5,319.3,324.1,326.8,324.3,313.9
23,NaN,कन िटक Karnataka,331.9,338.7,334.1,338.9,337.2,336.8,310.2
24,SR,केरल Kerala,97.4,99.5,102.8,102.5,95.9,99.5,93.0
25,NaN,तलमलन डु Tamil Nadu,416.5,424.0,411.3,419.9,426.8,424.5,379.2
26,NaN,पिु िु रे ी (पॉश्डडिरे ी) Pondy,10.3,10.4,10.1,10.4,10.5,10.8,10.4
27,,बिि र Bihar,128.5,132.3,134.7,136.7,134.9,144.2,133.7
28,पू०क्षे०\nER,डीवीसी DVC,69.9,68.7,68.7,70.8,69.5,71.7,68.2
29,NaN,झ रिडां Jharkhand,45.7,43.5,44.5,45.9,45.5,47.0,42.6
30,NaN,ओडडश Odisha,139.9,144.3,145.4,141.7,136.7,147.2,136.6
31,NaN,पश्चिम िगां ल West Bengal,214.0,200.6,213.0,236.0,246.2,253.8,208.9
32,NaN,लसश्ककम Sikkim,1.7,1.8,1.8,1.8,1.8,1.7,1.3
33,NaN,रेलवे Railways_ER ISTS,0.3,0.2,0.2,0.2,0.3,0.2,0.2
34,उ०पू०क्षे०\nNER,अरुण िल प्रिेश\nArunachal Pradesh,3.3,3.3,2.7,2.9,3.2,3.0,3.0
35,NaN,असम Assam,29.0,30.8,38.1,30.5,32.5,32.8,30.7
36,NaN,मखणपरु Manipur,3.4,3.3,3.4,3.3,3.1,3.4,3.2
37,NaN,मघे लय Meghalaya,6.2,6.0,5.6,5.8,5.7,6.3,5.7
38,NaN,लमर्ोरम Mizoram,2.0,2.1,2.0,2.1,2.0,2.0,2.1
39,NaN,न ग लडैं Nagaland,2.5,2.6,2.6,2.7,2.2,2.6,2.4
40,NaN,बत्रपरु Tripura,3.7,3.9,4.7,5.4,5.6,5.6,5.1
41,अखिल भ रतीय ALL INDIA,NaN,4986.2,4852.6,4849.3,4910.4,4865.7,4868.4,4562.6

In [14]:
raw_energy_df = extract_table_as_dataframe(
    pdf_path=pdf_path,
    page_number=energy_page_number,
    table_index=0
)

display(raw_energy_df)

,0,1,2,3,4,5,6,7,8
0,5. र ज्यों में ऊर् ि िपत (लमललयन यर्ू नर्ट्स)\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र Region,र ज्य States,30-03-2026,31-03-2026,01-04-2026,02-04-2026,03-04-2026,04-04-2026,05-04-2026
2,उ०क्षे०\nNR,पर्ां ि Punjab,154.8,150.2,151.3,157.1,158.0,154.2,140.1
3,NaN,िररय ण Haryana,158.5,154.2,150.2,158.9,155.8,153.1,132.6
4,NaN,र र्स्ि न Rajasthan,266.3,240.2,239.6,246.9,233.3,226.0,222.2
5,NaN,दिल्ली Delhi,93.0,84.4,88.9,93.6,93.4,88.4,85.5
6,NaN,उिर प्रिेश UP,422.6,423.3,395.5,429.2,411.5,373.3,344.2
7,NaN,उिर िडां Uttarakhand,42.9,42.6,41.7,41.8,44.5,43.9,39.5
8,,दिम िल प्रिेश HP,32.7,30.8,29.9,31.0,32.1,31.4,28.4
9,NaN,र्म्मू और कचमीर J&K,52.8,48.9,43.1,51.7,52.8,51.2,53.1
10,NaN,िडां ीगढ़ Chandigarh,4.0,3.8,4.0,4.0,4.0,3.9,3.5
11,NaN,रेलवे Railways_NR ISTS,4.2,4.1,4.2,4.2,4.2,4.2,4.3
12,,छिीसगढ़ Chhattisgarh,149.6,146.6,147.9,152.7,152.9,150.8,140.7
13,NaN,गर्ु र त Gujarat,471.1,473.6,449.0,450.2,450.0,447.1,426.5
14,,मध्य प्रिेश MP,274.7,269.2,277.7,268.3,253.5,264.4,254.0
15,प०क्षे०\nWR,मि र ष्ट्ट्र Maharashtra,659.1,617.0,636.3,589.9,582.2,605.2,590.2
16,NaN,गोव Goa,17.1,17.4,17.5,17.1,16.4,17.0,15.4
17,NaN,ि िर और नगर िवले ी एवां िमन और\nिीव DNHDDPDCL,29.3,29.3,27.1,26.9,28.4,28.7,26.7
18,NaN,एएमएनएसआईएल AMNSIL,20.6,19.6,20.5,20.8,18.3,19.0,19.4
19,NaN,ि ल्को BALCO,16.3,16.2,16.0,16.9,16.9,16.9,17.5
20,NaN,आर.आई.एल.र् मनगर\nRIL Jamnagar,5.9,6.2,6.4,6.2,6.3,6.3,6.3
21,ि०क्षे०,आध्रां प्रिेश Andhra Pradesh,264.0,261.8,257.6,261.3,265.2,265.9,262.5
22,NaN,तले गां न Telangana,341.1,297.5,319.3,324.1,326.8,324.3,313.9
23,NaN,कन िटक Karnataka,331.9,338.7,334.1,338.9,337.2,336.8,310.2
24,SR,केरल Kerala,97.4,99.5,102.8,102.5,95.9,99.5,93.0
25,NaN,तलमलन डु Tamil Nadu,416.5,424.0,411.3,419.9,426.8,424.5,379.2
26,NaN,पिु िु रे ी (पॉश्डडिरे ी) Pondy,10.3,10.4,10.1,10.4,10.5,10.8,10.4
27,,बिि र Bihar,128.5,132.3,134.7,136.7,134.9,144.2,133.7
28,पू०क्षे०\nER,डीवीसी DVC,69.9,68.7,68.7,70.8,69.5,71.7,68.2
29,NaN,झ रिडां Jharkhand,45.7,43.5,44.5,45.9,45.5,47.0,42.6
30,NaN,ओडडश Odisha,139.9,144.3,145.4,141.7,136.7,147.2,136.6
31,NaN,पश्चिम िगां ल West Bengal,214.0,200.6,213.0,236.0,246.2,253.8,208.9
32,NaN,लसश्ककम Sikkim,1.7,1.8,1.8,1.8,1.8,1.7,1.3
33,NaN,रेलवे Railways_ER ISTS,0.3,0.2,0.2,0.2,0.3,0.2,0.2
34,उ०पू०क्षे०\nNER,अरुण िल प्रिेश\nArunachal Pradesh,3.3,3.3,2.7,2.9,3.2,3.0,3.0
35,NaN,असम Assam,29.0,30.8,38.1,30.5,32.5,32.8,30.7
36,NaN,मखणपरु Manipur,3.4,3.3,3.4,3.3,3.1,3.4,3.2
37,NaN,मघे लय Meghalaya,6.2,6.0,5.6,5.8,5.7,6.3,5.7
38,NaN,लमर्ोरम Mizoram,2.0,2.1,2.0,2.1,2.0,2.0,2.1
39,NaN,न ग लडैं Nagaland,2.5,2.6,2.6,2.7,2.2,2.6,2.4
40,NaN,बत्रपरु Tripura,3.7,3.9,4.7,5.4,5.6,5.6,5.1
41,अखिल भ रतीय ALL INDIA,NaN,4986.2,4852.6,4849.3,4910.4,4865.7,4868.4,4562.6

In [15]:
print("Shape:", raw_energy_df.shape)

Shape: (42, 9)

In [16]:
display(raw_energy_df.head())

,0,1,2,3,4,5,6,7,8
0,5. र ज्यों में ऊर् ि िपत (लमललयन यर्ू नर्ट्स)\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र Region,र ज्य States,30-03-2026,31-03-2026,01-04-2026,02-04-2026,03-04-2026,04-04-2026,05-04-2026
2,उ०क्षे०\nNR,पर्ां ि Punjab,154.8,150.2,151.3,157.1,158.0,154.2,140.1
3,NaN,िररय ण Haryana,158.5,154.2,150.2,158.9,155.8,153.1,132.6
4,NaN,र र्स्ि न Rajasthan,266.3,240.2,239.6,246.9,233.3,226.0,222.2

In [17]:
display(raw_energy_df.tail())

,0,1,2,3,4,5,6,7,8
37,NaN,मघे लय Meghalaya,6.2,6.0,5.6,5.8,5.7,6.3,5.7
38,NaN,लमर्ोरम Mizoram,2.0,2.1,2.0,2.1,2.0,2.0,2.1
39,NaN,न ग लडैं Nagaland,2.5,2.6,2.6,2.7,2.2,2.6,2.4
40,NaN,बत्रपरु Tripura,3.7,3.9,4.7,5.4,5.6,5.6,5.1
41,अखिल भ रतीय ALL INDIA,NaN,4986.2,4852.6,4849.3,4910.4,4865.7,4868.4,4562.6

In [18]:
maximum_demand_pages = search_pdf(
    pdf_path,
    "Maximum Demand Met"
)

print(maximum_demand_pages)

[3]

In [19]:
maximum_demand_page_number = maximum_demand_pages[0]

In [20]:
maximum_tables = extract_tables_from_page(
    pdf_path,
    maximum_demand_page_number
)

print(
    "Tables detected on Maximum Demand page:",
    len(maximum_tables)
)

Tables detected on Maximum Demand page: 1

In [21]:
for index, table in enumerate(maximum_tables):

    shape = get_table_shape(table)

    print(
        f"Table {index}: "
        f"{shape['rows']} rows × "
        f"{shape['columns']} columns"
    )

Table 0: 42 rows × 16 columns

In [22]:
for index, table in enumerate(maximum_tables):

    print(f"\nTABLE {index}")

    temp_df = table_to_dataframe(table)

    display(temp_df.head(10))

TABLE 0

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,4. र ज्यों में दिन के िौर न अग्रिकतम म ांग आपर...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र\nRegion,दिन ांक Date,30-03-2026,NaN,31-03-2026,NaN,01-04-2026,NaN,02-04-2026,NaN,03-04-2026,NaN,04-04-2026,NaN,05-04-2026,NaN
2,NaN,र ज्य\nStates,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage
3,,पर्ां ि Punjab,7517,0,7441,0,7540,0,7579,0,7875,0,7277,0,6607,0
4,उ०क्षे०\nNR,िररय ण Haryana,7940,0,7225,0,7944,0,8489,0,7529,0,8302,0,7166,0
5,NaN,र र्स्ि न Rajasthan,12962,0,11326,0,11826,0,12382,0,11298,0,11019,0,10966,0
6,NaN,दिल्ली Delhi,4456,0,4375,0,4367,0,4597,0,4445,0,4244,0,3961,0
7,NaN,उिर प्रिेश UP,21561,0,21301,0,22168,0,22797,0,21509,0,19134,0,19252,0
8,NaN,उिर िडां Uttarakhand,2242,0,2276,0,2181,0,2256,0,2330,0,2272,0,2064,0
9,NaN,दिम िल प्रिेश HP,1783,0,1790,0,1678,0,1706,0,1740,0,1687,0,1645,0

In [23]:
try:
    extract_tables_from_page(
        pdf_path,
        page_number=999
    )

except ValueError as error:
    print("Expected error:", error)

Expected error: Page number must be between 1 and 6

In [24]:
try:
    extract_table_as_dataframe(
        pdf_path,
        page_number=energy_page_number,
        table_index=10
    )

except IndexError as error:
    print("Expected error:", error)

Expected error: table_index must be between 0 and 0.