# Table Validation

This notebook validates raw extracted tables without cleaning or transforming them. The workflow preserves the project boundary: **Extraction → Validation → Transformation**.

## 1. Project setup and imports

In [1]:
from pathlib import Path
import sys

import pandas as pd
from IPython.display import display

working_directory = Path.cwd()
project_root = (
    working_directory
    if (working_directory / "app").exists()
    else working_directory.parent
)

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

sample_documents = project_root / "sample_documents"

from app.extraction.table_extractor import extract_table_as_dataframe
from app.parsers.pdf_parser import search_pdf
from app.validation.table_validator import validate_table

print("Project root:", project_root)
print("Sample documents exists:", sample_documents.exists())

Project root: C:\Users\vinee\document-table-agent
Sample documents exists: True

## 2. Load the sample PDF

In [2]:
pdf_files = sorted(sample_documents.glob("*.pdf"))

if not pdf_files:
    raise FileNotFoundError("No PDF files found in sample_documents.")

pdf_path = pdf_files[0]
print("Using PDF:", pdf_path)

Using PDF: C:\Users\vinee\document-table-agent\sample_documents\Weekly 300326 to 050426_544 (1).pdf

## 3. Locate Energy Consumption with `search_pdf()`

In [3]:
energy_pages = search_pdf(pdf_path, "Energy Consumption")

if not energy_pages:
    raise ValueError("Energy Consumption was not found in the sample PDF.")

energy_page_number = energy_pages[0]
print("Energy Consumption pages:", energy_pages)

Energy Consumption pages: [4]

## 4. Extract the raw Energy Consumption table

In [4]:
raw_energy_df = extract_table_as_dataframe(
    pdf_path=pdf_path,
    page_number=energy_page_number,
    table_index=0,
)

print("Raw Energy table shape:", raw_energy_df.shape)
display(raw_energy_df.head())

Raw Energy table shape: (42, 9)

,0,1,2,3,4,5,6,7,8
0,5. र ज्यों में ऊर् ि िपत (लमललयन यर्ू नर्ट्स)\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र Region,र ज्य States,30-03-2026,31-03-2026,01-04-2026,02-04-2026,03-04-2026,04-04-2026,05-04-2026
2,उ०क्षे०\nNR,पर्ां ि Punjab,154.8,150.2,151.3,157.1,158.0,154.2,140.1
3,NaN,िररय ण Haryana,158.5,154.2,150.2,158.9,155.8,153.1,132.6
4,NaN,र र्स्ि न Rajasthan,266.3,240.2,239.6,246.9,233.3,226.0,222.2

## 5. Validate and display the Energy Consumption report

In [5]:
energy_before_validation = raw_energy_df.copy(deep=True)
energy_report = validate_table(raw_energy_df)
pd.testing.assert_frame_equal(
    raw_energy_df,
    energy_before_validation,
    check_exact=True,
)

display(pd.Series(energy_report, name="value").to_frame())

                                                                          value
rows                                                                         42
columns                                                                       9
missing_cells                                                                42
missing_values_by_column      {0: 33, 1: 2, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7:...
duplicate_rows                                                                0
duplicate_row_positions                                                      []
empty_rows                                                                   []
empty_columns                                                                []
non_empty_cells_per_row       [1, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, ...
possible_title_rows                                                         [0]
possible_header_rows                                                        [1]
date_like_cells                                                               7
date_like_cell_locations      [{'row': 1, 'column': 2, 'value': '30-03-2026'...
possible_hierarchical_header                                              False
possible_merged_cell_columns                                                [0]
warnings                      [42 missing or blank cells detected., Rows [0]...

## 6. Locate and extract Maximum Demand / Peak Shortage

In [6]:
maximum_demand_pages = search_pdf(pdf_path, "Maximum Demand Met")

if not maximum_demand_pages:
    raise ValueError("Maximum Demand Met was not found in the sample PDF.")

maximum_demand_page_number = maximum_demand_pages[0]
raw_maximum_demand_df = extract_table_as_dataframe(
    pdf_path=pdf_path,
    page_number=maximum_demand_page_number,
    table_index=0,
)

print("Maximum Demand pages:", maximum_demand_pages)
print("Raw Maximum Demand table shape:", raw_maximum_demand_df.shape)
display(raw_maximum_demand_df.head())

Maximum Demand pages: [3]
Raw Maximum Demand table shape: (42, 16)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,4. र ज्यों में दिन के िौर न अग्रिकतम म ांग आपर...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,क्षेत्र\nRegion,दिन ांक Date,30-03-2026,NaN,31-03-2026,NaN,01-04-2026,NaN,02-04-2026,NaN,03-04-2026,NaN,04-04-2026,NaN,05-04-2026,NaN
2,NaN,र ज्य\nStates,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage,दिन के\nिौर न\nअग्रिकतम\nम ांग आपर्ूति\nMax.\n...,अग्रिकतम\nम ांग के\nसमय कमी\nPeak hr\nShortage
3,,पर्ां ि Punjab,7517,0,7441,0,7540,0,7579,0,7875,0,7277,0,6607,0
4,उ०क्षे०\nNR,िररय ण Haryana,7940,0,7225,0,7944,0,8489,0,7529,0,8302,0,7166,0

## 7. Validate and display the Maximum Demand report

In [7]:
maximum_before_validation = raw_maximum_demand_df.copy(deep=True)
maximum_demand_report = validate_table(raw_maximum_demand_df)
pd.testing.assert_frame_equal(
    raw_maximum_demand_df,
    maximum_before_validation,
    check_exact=True,
)

display(pd.Series(maximum_demand_report, name="value").to_frame())

                                                                          value
rows                                                                         42
columns                                                                      16
missing_cells                                                                57
missing_values_by_column      {0: 35, 1: 1, 2: 1, 3: 2, 4: 1, 5: 2, 6: 1, 7:...
duplicate_rows                                                                0
duplicate_row_positions                                                      []
empty_rows                                                                   []
empty_columns                                                                []
non_empty_cells_per_row       [1, 9, 15, 15, 16, 15, 15, 15, 15, 15, 15, 15,...
possible_title_rows                                                         [0]
possible_header_rows                                                     [1, 2]
date_like_cells                                                               7
date_like_cell_locations      [{'row': 1, 'column': 2, 'value': '30-03-2026'...
possible_hierarchical_header                                               True
possible_merged_cell_columns                                                [0]
warnings                      [57 missing or blank cells detected., Rows [0]...

## 8. Compare validation results

In [8]:
comparison_fields = [
    "rows",
    "columns",
    "missing_cells",
    "duplicate_rows",
    "empty_rows",
    "empty_columns",
    "possible_title_rows",
    "possible_header_rows",
    "date_like_cells",
    "possible_hierarchical_header",
    "possible_merged_cell_columns",
]

comparison = pd.DataFrame(
    {
        "Energy Consumption": {
            field: energy_report[field] for field in comparison_fields
        },
        "Maximum Demand / Peak Shortage": {
            field: maximum_demand_report[field]
            for field in comparison_fields
        },
    }
)

display(comparison)

                             Energy Consumption Maximum Demand / Peak Shortage
rows                                         42                             42
columns                                       9                             16
missing_cells                                42                             57
duplicate_rows                                0                              0
empty_rows                                   []                             []
empty_columns                                []                             []
possible_title_rows                         [0]                            [0]
possible_header_rows                        [1]                         [1, 2]
date_like_cells                               7                              7
possible_hierarchical_header              False                           True
possible_merged_cell_columns                [0]                            [0]

## 9. Findings

- Validation is observational: both raw DataFrames are asserted identical before and after validation.
- Missing and blank cells are reported, not filled. Internal missing runs can suggest vertically merged group labels, but ordinary missing data can produce the same pattern.
- Title and header rows are heuristic candidates. The Maximum Demand table is expected to produce adjacent header candidates, which is reported cautiously as a possible hierarchical header.
- Date matching accepts only complete, valid date patterns; date-like values can occur in either headers or data.
- No state-name cleaning, bilingual-text removal, header flattening, reshaping, numeric conversion, or other transformation is performed.